title: <span style="color: green"> Puneet Panwar Some green text </span>
url: "https://puneet-panwar.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
